-- MySQL Script generated by MySQL Workbench
-- Tue Oct 14 15:48:57 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Loja_online
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Loja_online
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Loja_online` DEFAULT CHARACTER SET utf8 ;
USE `Loja_online` ;

-- -----------------------------------------------------
-- Table `Loja_online`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Loja_online`.`Produtos` (
  `idProdutos` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(50) NOT NULL,
  `Preco` DECIMAL NOT NULL,
  `Descricao` ENUM("Novo", "Usado", "Liquidacao", "Promocao", "Outros") NOT NULL,
  `Categoria` SET("Eletronico", "Telefonia", "Informatica", "Eletrodomesticos", "Acessorios", "Outros") NOT NULL,
  `Data_de_Lancamento` DATE NOT NULL,
  `Desconto` DECIMAL NOT NULL,
  PRIMARY KEY (`idProdutos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Loja_online`.`Caracteristica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Loja_online`.`Caracteristica` (
  `idCaracteristica` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCaracteristica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Loja_online`.`Produtos_Caracteristica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Loja_online`.`Produtos_Caracteristica` (
  `idProCar` INT NOT NULL AUTO_INCREMENT,
  `Produtos` INT NOT NULL,
  `Caracteristica` INT NOT NULL,
  INDEX `fk_Produtos_has_Caracteristica_Caracteristica1_idx` (`Caracteristica` ASC),
  INDEX `fk_Produtos_has_Caracteristica_Produtos_idx` (`Produtos` ASC),
  PRIMARY KEY (`idProCar`),
  CONSTRAINT `fk_Produtos_has_Caracteristica_Produtos`
    FOREIGN KEY (`Produtos`)
    REFERENCES `Loja_online`.`Produtos` (`idProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produtos_has_Caracteristica_Caracteristica1`
    FOREIGN KEY (`Caracteristica`)
    REFERENCES `Loja_online`.`Caracteristica` (`idCaracteristica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Loja_online`.`Loja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Loja_online`.`Loja` (
  `idLoja` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Endereco` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLoja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Loja_online`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Loja_online`.`Estoque` (
  `idEstoque` INT NOT NULL AUTO_INCREMENT,
  `Loja` INT NOT NULL,
  `Produtos` INT NOT NULL,
  `Quantidade` INT NOT NULL DEFAULT 0,
  INDEX `fk_Loja_has_Produtos_has_Caracteristica_Loja1_idx` (`Loja` ASC),
  PRIMARY KEY (`idEstoque`),
  INDEX `fk_Estoque_Produtos1_idx` (`Produtos` ASC),
  CONSTRAINT `fk_Loja_has_Produtos_has_Caracteristica_Loja1`
    FOREIGN KEY (`Loja`)
    REFERENCES `Loja_online`.`Loja` (`idLoja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estoque_Produtos1`
    FOREIGN KEY (`Produtos`)
    REFERENCES `Loja_online`.`Produtos` (`idProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
